[package]
name = "mjolnir_grafana"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
edition = "2018"

[dependencies]
mjolnir-api = {git = "https://github.com/ChrisMacNaughton/Mjolnir.git"}
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
